openapi: 3.0.0
info:
  title: Applications Search API
  description: "Able to search for an enrollment application and see all the details along with stauts. \n"
  contact:
    name: ABC
    url: https://inspirewellness.sharepoint.com/sites/EnterpriseAPIIntegration2
    email: TEST_Product_and_Portfolio_Team@test.com
    x-owner-snow-group-name: Ask the domain team for their SNow group Name
    x-sre-team-name: Ask the domain team for their SRE team name
  version: 2.0.0
servers:
- url: "https://{serverName}/{apiVersion}/{basePath}"
  description: The server URL for v2 Applications Search API
  variables:
    serverName:
      description: Name of the server
      default: dev-hapi-ugw1.test.com
      enum:
      - test
    basePath:
      description: Base path and folder for the API
      default: enrollment-search
    apiVersion:
      description: API version in URL
      default: v2
security:
- Apikey: []
- OAuth2:
  - APPLICATIONS.*.READ
  - APPLICATIONS.*.WRITE
paths:
  /applications/search:
    post:
      tags:
      - Search applications
      summary: Search submitted enrollment applications and get details
      description: |
        Search submitted enrollment applications and get details
      parameters:
      - name: offset
        in: query
        description: "Optional. This parameter is used to facilitate pagination of available results by providing an offset position to the results list. It can be sent by the consumer to indicate the starting point of the result set for the current call. The offset is a non-negative integer representing the first result to return. If not provided, it defaults the value of 0."
        schema:
          type: integer
        example: 0
      - name: limit
        in: query
        description: "Optional. Default is 50 records. This parameter is used to facilitate pagination by indicating a count of results to return in each page. The query parameter limit should be sent by the consumer to determine the number of results returned in the current call. The limit shall be a non-negative, non-zero integer indicating the maximum number of results to return at one time."
        schema:
          type: integer
        example: 50
      - name: x-system-name
        in: header
        description: Name of the channel or system which will be consuming the API. This name will help identify who made the request and log the request with the sytem name + system's user details.
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: x-user-id
        in: header
        description: Id of the user in the consuming channel or system who is making the request. This id help identify who made the request and log the request with the sytem name + system's user details.
        required: false
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/app-search-criteria-schema'
            examples:
              byApplicationId:
                summary: byApplicationId
                description: Applications can be search by Application Id independently
                value:
                  filters:
                    searchType: byApplicationId
                    applicationId: Av2325325
              byOfficialIdentifier:
                summary: byOfficialIdentifier
                description: Applications can be search by Medicare or Medicaid Id through official Identifiers block. Code "MC" should be used to search for apllications with "Medicare Id". Code "MA" should be used to search for applications with "Medicaid Id"
                value:
                  filters:
                    searchType: byOfficialIdentifier
                    identifierCode: MC
                    identifierValue: v12324
              byInternalIdentifier:
                summary: byInternalIdentifier
                description: Applications can be search by test internal Id like Member Card Id independently. identifierType "MemberCardId" should be used to search for apllications.
                value:
                  filters:
                    searchType: byOfficialIdentifier
                    identifierType: MemberCardId
                    identifierValue: H123456
              byDemographics:
                summary: byDemographics
                description: "Applications can be search by demographic information. \nTo search by person's name:  first name, last name, middle name needs to be provided with the combination of DOB or official Identifiers likes Medicaid id or Medicare Id.\nApplications can search by Email address alone.\nApplications can search by Phone number alone.\nApplications can search by DOB alone.\n"
                value:
                  filters:
                    searchType: byOfficialIdentifier
                    firstName: Joe
                    lastName: Doe
                    middleName: D
                    dateOfBirthDate: 1956-03-03
                    emailAddress: ""
                    phoneNumber: ""
                    state: ""
                    identifierCode: MC
                    identifierValue: v12324
              byVoiceLogId:
                summary: byVoiceLogId
                description: Applications can be search by telephone Signature Voice Log Id independently
                value:
                  filters:
                    searchType: byVoiceLogId
                    applicationTelephoneSignatureVoiceLogId: t2325325
              byDateRange:
                summary: byDateRange
                description: "Applications can be searched by applicationSignatureFromDate and  applicationSignatureToDate. if 'applicationSignatureFromDate' is provided in the request, 'applicationSignatureToDate' is required.\nApplications can be searched by applicationSubmittedFromDate and  applicationSubmittedToDate. If 'applicationSubmittedFromDate' is provided in the request, 'applicationSubmittedToDate' is required. \n"
                value:
                  filters:
                    searchType: byDateRange
                    applicationSubmittedFromDate: 2023-12-04
                    applicationSubmittedToDate: 2023-12-04
                    applicationSignatureFromDate: ""
                    applicationSignatureToDate: ""
              byAgent:
                summary: byAgent
                description: |
                  Applications can be searched by agent full name or system assigned number or  SSN with a combination of submitted from and to dates or signature from and to date.
                value:
                  filters:
                    searchType: byAgent
                    agentBrokerId: t2325325
                    agentBrokerName: Danielle Hansen
                    agentBrokerSocialSecurityNumber: "020609519"
                    applicationSubmittedFromDate: 2023-12-04
                    applicationSubmittedToDate: 2023-12-04
                    applicationSignatureFromDate: ""
                    applicationSignatureToDate: ""
              byLineOfBusiness:
                summary: byLineOfBusiness
                description: Applications can be searched by lineOfBusiness with a combination of submitted from and to dates or signature from and to date.
                value:
                  filters:
                    searchType: byLineOfBusiness
                    lineOfBusiness: Medicare
                    applicationSubmittedFromDate: 2023-12-04
                    applicationSubmittedToDate: 2023-12-04
                    applicationSignatureFromDate: ""
                    applicationSignatureToDate: ""
              byApplicationType:
                summary: byApplicationType
                description: "Applications can be searched by applicationType ( MA, MAPD PDP, OSB, CSNP, DSNP, SNP, ISNP, Med Supp, IDV) with a combination of submitted from andto dates or signature from and to date."
                value:
                  filters:
                    searchType: byApplicationType
                    applicationType: PDP
                    applicationSubmittedFromDate: 2023-12-04
                    applicationSubmittedToDate: 2023-12-04
                    applicationSignatureFromDate: ""
                    applicationSignatureToDate: ""
              byApplicationStatus:
                summary: byApplicationStatus
                description: Applications can be searched by applicationStatus with a combination of submitted from and to dates or signature from and to date
                value:
                  filters:
                    searchType: byApplicationStatus
                    applicationStatus: Submitted
                    applicationSubmittedFromDate: 2023-12-04
                    applicationSubmittedToDate: 2023-12-04
                    applicationSignatureFromDate: ""
                    applicationSignatureToDate: ""
              bySignatureType:
                summary: bySignatureType
                description: Applications can be searched by signatureType with a combination of submitted from and to dates or signature from and to date.
                value:
                  filters:
                    searchType: bySignatureType
                    applicationSignatureType: WetSignature
                    applicationSubmittedFromDate: 2023-12-04
                    applicationSubmittedToDate: 2023-12-04
                    applicationSignatureFromDate: ""
                    applicationSignatureToDate: ""
              byChannelCode:
                summary: byChannelCode
                description: Applications can be searched by enrollmentSourceCode with a combination of submitted from and to dates or signature from and to date.
                value:
                  filters:
                    searchType: byChannelCode
                    applicationEnrollmentSourceCode: CT
                    applicationSubmittedFromDate: 2023-12-04
                    applicationSubmittedToDate: 2023-12-04
                    applicationSignatureFromDate: ""
                    applicationSignatureToDate: ""
              byBrand:
                summary: byBrand
                description: Applications can be searched by brand with a combination of submitted from and to dates or signature from and to date.
                value:
                  filters:
                    searchType: byBrand
                    brand: test
                    applicationSubmittedFromDate: 2023-12-04
                    applicationSubmittedToDate: 2023-12-04
                    applicationSignatureFromDate: ""
                    applicationSignatureToDate: ""
        required: true
      responses:
        "200":
          description: status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/applications-search-response'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400Error'
        "401":
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404Error'
        "422":
          description: Unprocessable entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/422Error'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/500Error'
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/503Error'
components:
  schemas:
    apps-search-request-byApplicationId:
      required:
      - applicationId
      properties:
        applicationId:
          type: string
    apps-search-request-byVoiceLogId:
      required:
      - telephoneSignatureVoiceLogId
      allOf:
      - $ref: '#/components/schemas/application-voice-log-id-attribute'
    apps-search-request-byOfficialIdentifier:
      required:
      - identifierCode
      - identifierValue
      example:
        searchType: byOfficialIdentifier
        identifierCode: MC
        identifierValue: V123255436457
      allOf:
      - $ref: '#/components/schemas/official-identifier-code-attribute'
      - $ref: '#/components/schemas/identifier-value-attribute'
    apps-search-request-byInternalIdentifier:
      required:
      - identifierType
      - identifierValue
      example:
        searchType: byInternalIdentifier
        identifierType: MemberCardId
        identifierValue: H123456
      allOf:
      - $ref: '#/components/schemas/internal-identifier'
    apps-search-request-byDemographics:
      allOf:
      - $ref: '#/components/schemas/apps-search-request-demographic-block'
      - $ref: '#/components/schemas/official-identifier-code-attribute'
      - $ref: '#/components/schemas/identifier-value-attribute'
    apps-search-request-demographic-block:
      properties:
        firstName:
          type: string
        lastName:
          type: string
        middleName:
          type: string
        dateOfBirthDate:
          type: string
          format: date
        emailAddress:
          type: string
        phoneNumber:
          type: string
        state:
          type: string
    application-search-dates:
      properties:
        applicationSubmittedFromDate:
          type: string
          description: The date range from when test receives the application.
          format: date
        applicationSubmittedToDate:
          type: string
          description: The date range to when test receives the application.
          format: date
        applicationSignatureFromDate:
          type: string
          description: The date range from when an application was signed by the applicant
          format: date
        applicationSignatureToDate:
          type: string
          description: The date range to when an application was signed by the applicant
          format: date
    apps-search-request-ByAgent:
      allOf:
      - $ref: '#/components/schemas/agent-broker-Id-attribute'
      - $ref: '#/components/schemas/agent-broker-name-attribute'
      - $ref: '#/components/schemas/agent-broker-ssn-attribute'
      - $ref: '#/components/schemas/application-search-dates'
    apps-search-request-byDateRange:
      allOf:
      - $ref: '#/components/schemas/application-search-dates'
    apps-search-request-byLineOfBusiness:
      required:
      - lineOfBusiness
      allOf:
      - $ref: '#/components/schemas/line-of-business-attribute'
      - $ref: '#/components/schemas/application-search-dates'
    apps-search-request-byApplicationType:
      required:
      - applicationType
      allOf:
      - $ref: '#/components/schemas/application-type-attribute'
      - $ref: '#/components/schemas/application-search-dates'
    apps-search-request-byApplicationStatus:
      required:
      - applicationStatus
      properties:
        applicationStatus:
          type: string
          description: "Status of the application\n* Submitted  : when an application was received with an applicant's signature \n"
          enum:
          - Submitted
          - Completed
      allOf:
      - $ref: '#/components/schemas/application-search-dates'
    apps-search-request-bySignatureType:
      required:
      - applicationSignatureType
      allOf:
      - $ref: '#/components/schemas/application-signature-type-attribute'
      - $ref: '#/components/schemas/application-search-dates'
    apps-search-request-byChannelCode:
      required:
      - enrollmentSourceCode
      allOf:
      - $ref: '#/components/schemas/application-source-code-attribute'
      - $ref: '#/components/schemas/application-search-dates'
    apps-search-request-byBrand:
      required:
      - enrollmentSourceCode
      properties:
        brand:
          type: string
          description: "The company name.  test, CarePlus, ICare"
      allOf:
      - $ref: '#/components/schemas/application-search-dates'
    app-search-criteria-schema:
      properties:
        filters:
          type: object
          required:
            - searchType
          properties:
            searchType:
                type: string
          discriminator:
            propertyName: searchType
          oneOf:
          - $ref: '#/components/schemas/apps-search-request-byApplicationId'
          - $ref: '#/components/schemas/apps-search-request-byOfficialIdentifier'
          - $ref: '#/components/schemas/apps-search-request-byInternalIdentifier'
          - $ref: '#/components/schemas/apps-search-request-byDemographics'
          - $ref: '#/components/schemas/apps-search-request-ByAgent'
          - $ref: '#/components/schemas/apps-search-request-byVoiceLogId'
          - $ref: '#/components/schemas/apps-search-request-byDateRange'
          - $ref: '#/components/schemas/apps-search-request-byLineOfBusiness'
          - $ref: '#/components/schemas/apps-search-request-byApplicationType'
          - $ref: '#/components/schemas/apps-search-request-byApplicationStatus'
          - $ref: '#/components/schemas/apps-search-request-bySignatureType'
          - $ref: '#/components/schemas/apps-search-request-byChannelCode'
          - $ref: '#/components/schemas/apps-search-request-byBrand'
    applications-search-response:
      allOf:
      - $ref: '#/components/schemas/application-search-response'
      - $ref: '#/components/schemas/application-search-paginations-response'
      - $ref: '#/components/schemas/app-search-criteria-schema'
    application-search-response:
      properties:
        applications:
          type: array
          items:
            $ref: '#/components/schemas/applicationsearchresponse_applications'
    application-search-paginations-response:
      properties:
        pagination:
          $ref: '#/components/schemas/pagination-model'
        links:
          type: array
          description: "Optional. A list of pagination links, if applicable"
          example:
          - rel: self
            href: https://api.test.com/v2/enrollment-search/applications/search?offset=0&limit=50
          - rel: first
            href: https://api.test.com/v2/enrollment-search/applications/search?offset=0&limit=50
          - rel: prev
            href: https://api.test.com/v2/enrollment-search/applications/search?offset=0&limit=50
          - rel: next
            href: https://api.test.com/v2/enrollment-search/applications/search?offset=60&limit=50
          - rel: last
            href: https://api.test.com/v2/enrollment-search/applications/search?offset=200&limit=50
          items:
            $ref: '#/components/schemas/link-model'
    "400Error":
      properties:
        causes:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/exception-state'
      allOf:
      - $ref: '#/components/schemas/exception-state'
      - type: object
    exception-state:
      type: object
      properties:
        code:
          type: string
          description: A case-insensitive alpha-numeric identifier for the error.
          example: invalid.login
        description:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem. This should focus on helping the client correct the problem rather than debugging information.
          example: Sample description for error
        timestamp:
          type: string
          description: An ISO 8601 date/time in UTC indicating when the error occurred
          example: 2022-02-15T22:14:45.624+0000
        status:
          type: string
          description: The HTTP status code generated by service for this occurrence of the problem.
          example: "401"
        path:
          type: string
          description: A URI reference that identifies the Enterprise API resource which produced the problem
          example: v2/current-resource-name/A1
        traceId:
          type: string
          description: a trace identifier which may be used to consult logs and telemetry infrastructure regarding the error
          example: 1234HH4445
    "404Error":
      properties:
        causes:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/exception-state'
      allOf:
      - $ref: '#/components/schemas/exception-state'
      - type: object
    "422Error":
      type: object
      properties:
        message:
          type: string
          description: The error message associated with procesing failure
          example: Validation Failed
        timestamp:
          type: string
          description: An ISO 8601 date/time in UTC indicating when the error occurred
          example: 2022-02-15T22:14:45.624+0000
        status:
          type: integer
          description: The HTTP status code generated by service for this occurrence of the problem.
          example: 422
        code:
          type: string
          description: A case-insensitive alpha-numeric identifier for the error. The collection of expected error codes should be documented within the OpenAPI specification.
          example: P5ABCD
        path:
          type: string
          description: A URI reference that identifies the Enterprise API resource which produced the problem.
          example: v1/resource/12345/sub-resource-name-here
        description:
          type: string
          description: A description of the specific error
          example: Error XYZ from back-end ABC
        traceId:
          type: string
          description: a trace identifier which may be used to consult logs and telemetry infrastructure regarding the error
          example: 1234HH4445
        causes:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/exception-state'
    "500Error":
      properties:
        causes:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/exception-state'
      allOf:
      - $ref: '#/components/schemas/exception-state'
      - type: object
    "503Error":
      properties:
        causes:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/exception-state'
      allOf:
      - $ref: '#/components/schemas/exception-state'
      - type: object
    application-voice-log-id-attribute:
      properties:
        applicationTelephoneSignatureVoiceLogId:
          type: string
          description: Telephone Signature VoiceLog Id is available after Telephone Signature process is completed. It is the recording id from a vendor
    official-identifier-code-attribute:
      properties:
        identifierCode:
          type: string
          description: "Identifier code of the applicant, based on the lookup (https://terminology.hl7.org/4.0.0/CodeSystem-v2-0203.html#v2-0203-MR):\n * `MC` - Medicare Id\n * `MA` - Medicaid Id\n * `SS` - Social Security number\n * `MCN` - Medicaid Case Number \n    Medicaid Case Number ties a family or household together\n \n"
          example: MC
          enum:
          - MC
          - MA
          - SS
          - MCN
    identifier-value-attribute:
      properties:
        identifierValue:
          type: string
          description: Value of the identifier
    internal-identifier:
      properties:
        identifierType:
          type: string
          description: "Name of the identifier\n* MemberCardId - This is the number which is on the insurance Card. Also called as HNumber , Member Card Id, Member Id\n* Enterprise Member Id - Unique identifier for a person after being mastered. \n"
          enum:
          - MemberCardId
          - EnterpriseMemberId
      allOf:
      - $ref: '#/components/schemas/identifier-value-attribute'
    agent-broker-Id-attribute:
      properties:
        agentBrokerId:
          type: string
          description: System assigned number of an agent or a broker
          example: "1129696"
    agent-broker-name-attribute:
      properties:
        agentBrokerName:
          type: string
          description: Name of an agent or a broker
          example: Danielle Hansen
    agent-broker-ssn-attribute:
      properties:
        agentBrokerSocialSecurityNumber:
          type: string
          description: Social secuirty number of an agent or a broker
          example: "020609519"
    line-of-business-attribute:
      properties:
        lineOfBusiness:
          type: string
          description: Line of business of the plan.
          example: Medicare
          enum:
          - Commercial
          - Medicare
          - Medicaid
          - testOne
    application-type-attribute:
      properties:
        applicationType:
          type: string
          description: "Product type of the application. Type of application which was submitted. MA, MAPD PDP, OSB, CSNP, DSNP, SNP, ISNP, Med Supp, IDV"
          example: PDP
    application-signature-type-attribute:
      properties:
        applicationSignatureType:
          type: string
          description: "dfcew"
          enum:
          - WetSignature
          - ElectronicSignature
          - DigitalSignature
          - TelephonicSignature
          - Unsigned
          - InteractiveVoiceResponseSignature
          - ShortMessageServiceSignature
    application-source-code-attribute:
      properties:
        applicationEnrollmentSourceCode:
          type: string
          description: "Application enrollment source system(Channel). A sales entity used a particular route/connection to send applications to test.\n\nE1 and E7 are deprecated but applications can be search by these channels for legacy data\n\n* CT - Consumer TSR\n* DA - Digital API - Enrollment\n* DM - Digital Sales Material\n* DV - VIPR-D2C\n* E0 - Delegated Agent D2C\n* E1 - MAPA \n* E2 - FastApp Delegated Agent\n* E3 - FastApp TSR\n* E4 - D2C- Direct to Consumer\n* E5 - Delegated Agent (Med Sup only)\n* E6 - FastApp Delegated TSR\n* E7 - MAPA\n* E8 - Careplus\n* E9 - Abbreviated Enrollment Form\n* EC - D2C Click2Chat\n* ED - Delegated AEF\n* EM - Captive AEF\n* EN - Autoamted Full IVR\n* EW - Web AEF\n* MS - MedSupp EDI\n* OC - VIPR-Omni\n* PA - Acs Medsupp app\n* Q1 - EH 1.0 Captive\n* Q7 - EH 1.0 Delegated\n* S1 - EH 2.0 Captive\n* S7 - EH 2.0 Delegated\n* VP - VIPR Pro\n"
          example: CT
    pagination-model:
      properties:
        offset:
          type: integer
          example: 0
        limit:
          type: integer
          example: 20
        countOfItems:
          type: integer
          example: 1000
        countOfPages:
          type: integer
          example: 50
      description: Pagination attributes
    link-model:
      properties:
        rel:
          type: string
          description: Name of the sub-resource
        href:
          type: string
          description: Path to the sub-resource
    applicationsearchresponse_applications:
      properties:
        applicationId:
          type: string
        applicationStatus:
          type: string
          example: Submitted
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://login.microsoftonline.com/56c62bbe-8598-4b85-9e51-1ca753fa50f2/oauth2/v2.0/token
          scopes:
            read: Grants read access
            write: Grants write access
            admin: Grants access to admin operations
    Apikey:
      type: apiKey
      name: x-apikey
      in: header
